import CustomNavbar from "../components/CustomNavbar"

const About = () => {
    return (

<div className="container">
    <header>
        <CustomNavbar/>
    </header>
    <main>
        <section>
            <div>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eu sollicitudin ipsum, a euismod nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer mauris velit, volutpat cursus bibendum non, molestie sit amet dui. Vivamus ornare, leo sit amet mattis lobortis, urna sem luctus nibh, eleifend porta justo sapien vel lacus. Phasellus fermentum mi sit amet placerat sollicitudin. Nulla ac enim in odio pretium dapibus nec sit amet libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur nisi ante, varius ac enim id, sagittis pellentesque justo. Praesent porta finibus mi a lobortis.

Curabitur ornare massa vitae lorem elementum, non mattis enim ullamcorper. Vivamus quis lectus scelerisque, volutpat erat eu, tempor orci. Sed aliquet feugiat ipsum. In hac habitasse platea dictumst. Nam finibus, enim non mattis efficitur, magna velit tristique purus, in ultricies turpis orci nec massa. Fusce risus orci, finibus iaculis justo et, porttitor volutpat quam. Nam eu leo eget mi tempus dignissim nec ut augue. Integer vitae viverra purus.

Ut ornare felis tincidunt fringilla gravida. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris id lacus augue. Vestibulum posuere ut tortor et auctor. Nullam tempus posuere ultrices. Fusce a lobortis ipsum. Aliquam ornare, felis et cursus semper, nibh urna mattis felis, eget congue sapien quam eu urna. Vestibulum varius dui vitae dapibus sollicitudin. Vivamus euismod auctor tortor, eget lacinia ipsum posuere a. Aliquam erat volutpat. Etiam suscipit nunc sit amet tellus mollis tempor. Nam tempus bibendum vulputate. Aenean molestie, ipsum vitae bibendum malesuada, metus mi mollis felis, et euismod felis arcu eget tellus. Ut tortor arcu, pretium a tellus a, viverra semper nibh. Curabitur ultrices ligula sem, at faucibus nisi sodales congue. Quisque lobortis ipsum sed urna dapibus pellentesque.

Curabitur lectus sapien, tincidunt non arcu eget, fermentum tristique neque. Sed dictum luctus maximus. In maximus cursus mauris, a hendrerit magna ullamcorper eget. Maecenas vestibulum, eros non maximus convallis, justo turpis congue magna, a volutpat odio erat id justo. Praesent non lectus ut magna imperdiet bibendum vel vitae tellus. In hac habitasse platea dictumst. Pellentesque at dui a lacus pharetra tristique eu et lectus.

Vestibulum pellentesque risus vel nisi semper faucibus. Nam vehicula risus et est mattis, et suscipit enim posuere. Fusce maximus tortor ut risus fermentum, at bibendum tortor accumsan. Fusce sed elit ut risus pharetra tincidunt. Etiam nec diam ut metus aliquam rutrum. Nam placerat tellus semper nisl rhoncus, vel pellentesque purus posuere. Nullam non neque nibh. Duis sed ipsum sed lorem rutrum ornare. Donec fringilla augue sed cursus dictum. Ut diam purus, pellentesque finibus mauris eget, malesuada volutpat dui. Vivamus nisl ante, commodo eu augue id, convallis placerat ipsum. In ex sapien, sagittis lacinia dapibus quis, mollis vitae ex.

Maecenas sed volutpat dui. Nulla ultricies bibendum metus, eget convallis purus porttitor et. Morbi non tortor sem. Suspendisse risus lectus, mattis vitae arcu eget, condimentum scelerisque tellus. Nunc placerat odio id libero lacinia vulputate. In hac habitasse platea dictumst. Praesent eu bibendum ipsum, ullamcorper luctus tellus. Nunc ac vulputate felis. Donec eget urna eget ligula vehicula ultricies.

Aenean ac elementum lacus, venenatis rhoncus nunc. Nam ullamcorper lacus in eros tempus efficitur. Cras malesuada accumsan diam, ac ultricies tellus viverra ac. Quisque malesuada, ante vitae facilisis efficitur, metus sem molestie diam, in euismod purus ligula in velit. Nullam bibendum ante quis blandit bibendum. Nulla ante augue, sagittis sit amet velit in, pulvinar accumsan eros. Curabitur turpis nibh, vestibulum nec lectus id, sollicitudin accumsan elit. Suspendisse faucibus blandit tortor, et tempus metus tempus nec. In feugiat massa sed leo suscipit blandit. Nullam pellentesque elementum porta. Nunc at dictum odio.

Vivamus faucibus at dolor sit amet viverra. Cras convallis est ac leo sollicitudin viverra. Suspendisse et dui ac nibh ultrices tempor. Morbi tristique malesuada justo. Sed fermentum finibus luctus. Etiam vulputate varius ligula, quis dapibus elit cursus a. Vestibulum quis consectetur dui. Nullam aliquet ex a eros ornare, eu tristique mi iaculis. Nam blandit, felis et finibus dignissim, dui tortor pretium mauris, at scelerisque quam libero sit amet nibh. Fusce nec dolor id nunc tempus condimentum ac eget lorem. Curabitur tincidunt sem sit amet mauris interdum, et dictum velit malesuada.

Quisque tempor eros at felis sodales, sed finibus orci varius. Vestibulum lacus nunc, dictum eget bibendum pellentesque, facilisis a quam. Morbi commodo eros vel neque pretium, egestas faucibus turpis luctus. Vestibulum posuere nibh eget urna rhoncus posuere. Pellentesque accumsan iaculis elit, nec sodales massa laoreet ac. Nunc erat urna, vulputate vitae felis vel, aliquam venenatis lorem. Etiam tellus felis, dignissim sit amet neque ut, placerat sollicitudin leo.

Phasellus vulputate auctor est eu congue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum vel mauris lorem. Curabitur mollis massa at massa molestie, vel imperdiet urna tincidunt. In vel tortor ullamcorper sapien pharetra interdum sed sit amet enim. Sed ornare nisl in orci dignissim euismod. Nam ut magna turpis. Morbi sem tortor, posuere in rutrum eu, finibus tincidunt enim.

Fusce rutrum nibh metus, vitae condimentum urna ultricies sit amet. Proin luctus dolor sit amet ante congue ornare. Morbi turpis nisl, consectetur id ornare eget, accumsan nec nisi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean eros ipsum, sagittis at ligula id, posuere laoreet magna. Aliquam tristique quam eu nisl pharetra, vitae eleifend eros tempor. Maecenas in leo sit amet diam dignissim pellentesque. Fusce lacus tortor, elementum sit amet interdum sed, sodales sed enim. Integer ac ipsum velit. Mauris non blandit erat. Morbi nunc ante, suscipit ut mi ut, ornare tristique dui. Vestibulum luctus vitae ipsum at luctus. Vestibulum eget tempor eros, eu fermentum felis. Donec enim lacus, convallis eu mi quis, pretium placerat magna. Suspendisse lacus eros, semper vel aliquet a, ullamcorper sed massa.

Duis viverra metus nec nisi laoreet auctor. Vivamus nec augue dui. Nulla orci nisl, cursus sit amet feugiat et, malesuada eu purus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam nec volutpat purus. Quisque dictum felis vitae felis ultricies, sit amet efficitur neque vulputate. Integer pharetra sem finibus urna vulputate, et porttitor metus elementum. Donec cursus non mauris id pharetra.

Fusce rutrum nibh placerat mi volutpat consequat. Nam tempor ex sit amet tortor malesuada, ac luctus magna tincidunt. Vivamus laoreet odio eu eros tincidunt, et congue tellus tempus. Praesent id feugiat nisi. Nulla facilisi. Donec ultricies, turpis molestie laoreet pharetra, orci nunc feugiat enim, eget tempus risus neque et nulla. Nam id orci eget metus suscipit faucibus et eget magna. Phasellus porta diam vitae ultricies dapibus. Cras congue dui eget orci blandit, varius lobortis justo convallis. Morbi a suscipit risus. Nulla vitae bibendum ex. Etiam suscipit neque non convallis iaculis. Integer pharetra dolor at sagittis euismod.

Vivamus tincidunt accumsan cursus. Sed ac mi est. Curabitur vitae justo semper, aliquam dolor et, ullamcorper enim. Pellentesque turpis dui, tincidunt ut blandit a, finibus id lorem. Nam porttitor augue ac bibendum convallis. Proin ornare velit non porta ultrices. Ut odio neque, dapibus sit amet nisi quis, placerat venenatis lacus.

Vivamus vel nibh tristique, molestie metus non, egestas elit. In vel mattis est. Cras blandit et massa vel ultricies. Praesent elit felis, congue at sagittis interdum, elementum quis magna. Nulla egestas efficitur consectetur. Nam ultrices laoreet leo, eget tempus metus semper bibendum. Cras molestie sollicitudin tincidunt.

Suspendisse rutrum congue erat at pellentesque. Duis pharetra faucibus justo at maximus. Nullam bibendum leo ullamcorper ante maximus, vitae dapibus magna maximus. Praesent facilisis nulla quis auctor lacinia. Fusce suscipit, libero quis vehicula efficitur, lectus urna euismod ligula, dictum imperdiet nisl lorem quis mi. Proin et quam feugiat, eleifend velit eu, lobortis dui. Vestibulum efficitur mollis dolor at sollicitudin. Quisque semper lacus mattis massa lacinia pellentesque. Curabitur ex est, semper et commodo ut, posuere ultrices lacus. Vestibulum posuere, ligula sed elementum porttitor, lacus justo cursus lectus, congue rhoncus lectus nisl quis ante. Nullam ornare vel elit at dapibus. Integer imperdiet nisl vel leo maximus condimentum. Nullam rutrum at felis sagittis laoreet.

Vestibulum tincidunt nisl eget enim venenatis ultrices. Donec vel leo dictum, lobortis tortor tincidunt, finibus lectus. Nullam non interdum purus. Integer et egestas velit, vel posuere lacus. Vestibulum quis sem a erat vestibulum lobortis. Vivamus consequat orci magna, in mattis arcu tempor nec. Sed iaculis eros neque, et laoreet lacus porta quis. In hac habitasse platea dictumst. Suspendisse aliquam ipsum ex, mattis congue arcu sodales at. In tincidunt porttitor sapien quis egestas. Sed dignissim porttitor dignissim.

Nulla a risus scelerisque, pulvinar sem a, ultricies nulla. Proin venenatis a massa feugiat auctor. Nunc congue tellus est. Sed in libero tempus erat dapibus aliquet eu et arcu. Phasellus suscipit euismod viverra. Quisque dignissim congue convallis. Integer vestibulum quam sed nulla euismod, in condimentum arcu blandit. Nunc vestibulum ligula nibh, id porttitor ligula aliquet sed. Maecenas nec mauris fringilla, tincidunt ligula in, vehicula diam. Nulla facilisi. In pharetra ultrices porta. Ut aliquam libero eget purus porta sodales.

Ut nec nisi vel dui auctor tempor eu vel libero. Sed a dolor nunc. Cras dictum libero ex, nec vehicula felis aliquet sit amet. Etiam fermentum posuere lorem, quis feugiat leo faucibus sed. Nunc venenatis orci nec risus pulvinar blandit. Praesent sagittis bibendum magna eu interdum. Integer laoreet ante felis, et fringilla enim auctor in. Vestibulum sed erat id elit ornare commodo. Morbi facilisis risus faucibus aliquet facilisis. Nullam tincidunt cursus purus ut cursus. Etiam viverra magna in arcu fringilla, ut aliquam quam congue.

Donec id leo lectus. Nullam pharetra tempus convallis. Donec sit amet orci nibh. In vulputate justo id nulla sollicitudin sodales. Donec porta elementum maximus. Praesent ut odio felis. Aenean arcu purus, ornare vitae quam non, efficitur rhoncus mi. Pellentesque nec suscipit justo. Aenean lobortis tristique dui, vitae ultrices lorem pretium vitae. Quisque sed pellentesque magna, mollis volutpat libero. Fusce vitae risus urna. Vivamus tortor sapien, lacinia eu urna eget, dignissim fringilla sem. Nam ut vulputate leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent suscipit cursus massa, a iaculis lacus mattis venenatis.
            </div>
        </section>
    </main>
</div>
    )
}
export default About